version: '3.8'

services:
    # Server container
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/logs:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            app:
                condition: service_started
        ports:
            - "9090:80"

    # PHP FastCGI Process Manager container
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        depends_on:
            db:
                condition: service_started
        volumes:
            - .:/var/www/app

    # database
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "laravel_db"
            MYSQL_USER: "laravel"
            MYSQL_PASSWORD: "laravel"

    # testing database
    db_test:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "laravel_db_test"
            MYSQL_USER: "laravel"
            MYSQL_PASSWORD: "laravel"

    # Mailhog container (SMTP testing)
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8026:8025"
